#!/bin/sh

## SixtySecondShell generic esolang launh script

## This file will launch a Docker container with the esolang/$2 image, running $2.
# Note that $2 is the second argument passed into the script, the first being the file name of the script.

# The server will pass us the file name, which we will pass to the container

# For convienience
LANG="$2"

echo "=== SixtySecondShell Shell-Less Execution Runtime ==="
echo "Launching environment $1"
echo

# Note that since this is docker-in-docker, we make the volume reference relative to the HOST machine.
# Not a great solution, temporary until refactor.
docker run --rm -v "/home/ec2-user/sixtysecondshell/__code_store":/root/__code_store -it --network none "esolang/${LANG}" "${LANG}" "__code_store/$1"

echo
echo "=== S3 runtime ended. ==="