#!/bin/sh

## SixtySecondShell launch script for Evil

## This file will launch a Docker container with the esolang/evil image, running evil.

# This programming language is shell-less - it does NOT come with a REPL.
# Therefore, we are using the shell-less execution runtime to load the file into the container.

# The server will pass us the file name, which we will pass to the container

# For convienience
LANG="evil"

echo === SixtySecondShell Shell-Less Execution Runtime ===
echo "Launching environment $1"
echo

# Note that since this is docker-in-docker, we make the volume reference relative to the HOST machine.
# Not a great solution, temporary until refactor.
docker run --rm -v "/home/ec2-user/sixtysecondshell/__code_store":/root/__code_store -it --network none "esolang/${LANG}" "${LANG}" "__code_store/$1"

echo
echo "=== S3 runtime ended. ==="