#!/bin/sh

#################################################### 
# Note: there seems to be an issue with the
# esolang/spl image. Therefore, SPL is currently
# inactive. DO NOT REFERENCE THIS SCRIPT IN
# languages.config.js
####################################################

## SixtySecondShell launch script for Shakespeare Programming Language

## This file will launch a Docker container with the esolang/spl image, running spl.

# This programming language is shell-less - it does NOT come with a REPL.
# Therefore, we are using the shell-less execution runtime to load the file into the container.

# The server will pass us the file name, which we will pass to the container

echo === SixtySecondShell Shell-Less Execution Runtime ===
echo "Launching environment $1"
echo

# Note that since this is docker-in-docker, we make the volume reference relative to the HOST machine.
docker run --rm -v "/home/ec2-user/sixtysecondshell/__code_store":/root/__code_store -it esolang/spl spl "__code_store/$1"

echo
echo "=== S3 runtime ended. ==="