#!/bin/sh

## This will run a docker container with the Python image and use stdout
## It only consists of one command but must be its own file because otherwise we couldn't spawn a PTY from node-pty.

# Network is disabled until I find a workaround to use iptables in Alpine, otherwise one could grab EC2 metadata

docker run --rm -it --network none python python